FROM ubuntu:22.04 AS builder

ENV DEBIAN_FRONTEND=noninteractive

# TODO: 在 builder stage 下載並編譯 srsRAN gNB，需支援 ZMQ。

FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# TODO: 安裝 gNB runtime 需要的 library。
# TODO: 從 builder 複製 gNB binary，並準備 gNB 設定檔。
# TODO: 設定 container 啟動時執行 gNB。
