# TODO: 填入 srsUE 設定。
# 提示: 需要設定 ZMQ radio、NR band/PRB、USIM/IMSI/key/opc、APN/DNN 與 gateway 介面。
# 提示: UE 的 IMSI/PLMN 需要和 MongoDB subscriber 與 core 設定一致。

[usim]
opc = E8ED289DEBA952E4283B54E88E6183CA
k = 465B5CE8B199B49FAA5F0A2EE238A6BC
imsi = 001010000000001
imei = 356938035643803
algo = milenage

[rf]
device_name = zmq
device_args = tx_port=tcp://*:2001,rx_port=tcp://lab6-gnb:2000,id=ue,base_srate=11.52e6
srate = 11.52e6
nof_antennas = 1
tx_gain = 80
rx_gain = 40

[log]
all_level = info

[gw]
netns =
ip_devname = tun_srsue
ip_netmask = 255.255.255.0

[rat.eutra]
dl_earfcn = 2850
nof_carriers = 0

[rat.nr]
bands = 3
nof_carriers = 1
sa = true